apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds shuffle namespace to all resources.
namespace: shuffle      

resources:
  - all-in-one.yaml
  - ingress.yaml
  - configmaps/internal_users.yml
  - secrets/shuffle-backend-secrets.yaml
  - secrets/opensearch-secret.yaml